---
spring:
  application:
    name: ss-course-registration
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: h2
    url: jdbc:h2:file:~/test
    driverClassName: org.h2.Driver
    data: classpath:data-h2.sql
    initialization-mode: always
    username: sa
    password:
  sql:
    init:
      platform: h2
      mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false #not using DTO to return response, using direct entity needs this property.

server:
  port: 8888
